# Generated by Django 6.0.2 on 2026-02-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 24 Seater Bus or Mercedes S Class', max_length=200)),
                ('price_tag', models.CharField(default='Luxury Car', max_length=100)),
                ('seat_count', models.CharField(default='4+1', max_length=50)),
                ('main_image', models.ImageField(upload_to='vehicles/main/')),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='vehicles/side/')),
                ('interior_image', models.ImageField(blank=True, null=True, upload_to='vehicles/interior/')),
                ('has_ac', models.BooleanField(default=True, verbose_name='Has AC')),
                ('has_speaker', models.BooleanField(default=True, verbose_name='Has Speaker System')),
                ('has_tv', models.BooleanField(default=False, verbose_name='Has TV')),
                ('luggage_capacity', models.IntegerField(default=5)),
                ('main_description', models.TextField()),
                ('sub_desc_1_content', models.TextField(blank=True)),
                ('sub_desc_2_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
