# Generated by Django 6.0.2 on 2026-02-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/front/'),
        ),
    ]
