# Generated by Django 6.0.2 on 2026-02-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_vehicle_front_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Kashmir Holiday Tour', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly name (e.g., kashmir-holiday-tour)', unique=True)),
                ('image', models.ImageField(upload_to='tours/')),
                ('duration_days', models.IntegerField(help_text='Number of days')),
                ('duration_nights', models.IntegerField(help_text='Number of nights')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overview', models.TextField()),
                ('itinerary', models.TextField(help_text='Detailed day-by-day plan')),
                ('inclusions', models.TextField(help_text='What is included (one per line)')),
                ('exclusions', models.TextField(help_text='What is NOT included')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
