# Generated by Django 6.0.2 on 2026-02-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_tourpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('car', 'Luxury Car'), ('bus', 'Bus / Traveler'), ('van', 'Van')], default='car', max_length=10),
        ),
    ]
