# Generated by Django 6.0.2 on 2026-02-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_vehicle_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Feedback Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
